- nltk==3.7
- ale-py==0.8.1
- alembic==1.10.2
- async-generator==1.10
- autorom==0.4.2
- autorom-accept-rom-license==0.4.2
- bleach==3.2.2
- bqplot==0.12.39
- branca==0.6.0
- certipy==0.1.3
- click-plugins==1.1.1
- clifford==1.4.0
- cligj==0.7.2
- cloudpickle==1.6.0
- contourpy==1.0.7
- distlib==0.3.6
- dm-tree==0.1.8
- exceptiongroup==1.1.1
- farama-notifications==0.0.4
- filelock==3.12.0
- fiona==1.9.3
- folium==0.14.0
- frozendict==2.3.7
- gensim==4.3.1
- geographiclib==2.0
- geojson==3.0.1
- geopandas==0.12.2
- geopy==2.3.0
- grpcio==1.43.0
- gym==0.26.2
- gym-notices==0.0.8
- gymnasium==0.26.3
- gymnasium-notices==0.0.1
- h11==0.14.0
- html5lib==1.1
- importlib-resources==5.12.0
- inflection==0.5.1
- ipyleaflet==0.17.2
- jax-jumpy==1.0.0
- jupyter-client==7.4.1
- jupyter-telemetry==0.1.0
- jupyterhub==3.1.1
- jupyterlab-pygments==0.2.2
- lazy-loader==0.2
- llvmlite==0.39.1
- lz4==4.3.2
- mako==1.2.4
- markupsafe==2.1.2
- mistune==2.0.5
- more-itertools==9.1.0
- mplcursors==0.5.2
- mplleaflet==0.0.5
- msgpack==1.0.5
- multiapp==1.0
- multitasking==0.0.11
- munch==2.5.0
- nbclient==0.7.2
- nbconvert==7.3.1
- networkx==3.1
- nxviz==0.7.4
- osmpythontools==0.3.5
- outcome==1.2.0
- palettable==3.3.3
- pamela==1.0.0
- panel==0.14.4
- param==1.13.0
- patsy==0.5.3
- pip==23.0.1
- portpicker==1.5.2
- pot==0.9.0
- pygame==2.1.3.dev8
- pyproj==3.5.0
- pyqt5-sip==12.11.0
- pyrsistent==0.19.3
- python-json-logger==2.0.7
- pyviz-comms==2.2.1
- pywavelets==1.4.1
- quarto==0.1.0
- ray==2.1.0
- ruamel-yaml==0.17.21
- ruamel-yaml-clib==0.2.7
- scikit-image==0.20.0
- selenium==4.8.3
- shapely==2.0.1
- shimmy==0.2.1
- smart-open==6.3.0
- sortedcontainers==2.4.0
- soupsieve==2.4
- sparse==0.14.0
- sqlalchemy==2.0.7
- squarify==0.4.3
- statsmodels==0.13.5
- streamlit-folium==0.11.1
- swig==4.1.1
- tabulate==0.9.0
- tensorboardx==2.6
- tifffile==2023.4.12
- traittypes==0.2.1
- trimesh==3.21.5
- trio==0.22.0
- trio-websocket==0.10.2
- typer==0.7.0
- ujson==5.7.0
- virtualenv==20.21.0
- voila==0.4.0
- webencodings==0.5.1
- websockets==11.0.1
- wordcloud==1.9.1.1
- wsproto==1.2.0
- xarray==2023.4.2
- xyzservices==2023.2.0
